PERTEMUAN 9 TOPIK ANALISIS PYTHON

In [7]:
import numpy as np
arr1d = np.array([1,2,3,4,5])
print("Array ID:\n", arr1d)

arr2d = np.array([[1,2,3], [4,5,6]])
print("Array 2D:\n", arr2d)

Array ID:
 [1 2 3 4 5]
Array 2D:
 [[1 2 3]
 [4 5 6]]


In [8]:
import pandas as pd
data={'Nama':['Akim','Hanif','rahmat'],
      'usia':[25, 15, 10],
      'kota':['surabaya','bogor','sidoarjo']}
df = pd.DataFname(data)
print(df)

ModuleNotFoundError: No module named 'pandas'

In [9]:
pip install pandas

   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
    --------------------------------------- 0.3/11.1 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.1 MB 999.1 kB/s eta 0:00:11
   -- ------------------------------------- 0.8/11.1 MB 1.1 MB/s eta 0:00:10
   --- ------------------------------------ 1.0/11.1 MB 1.2 MB/s eta 0:00:09
   ---- ----------------------------------- 1.3/11.1 MB 1.2 MB/s eta 0:00:09
   ----- ---------------------------------- 1.6/11.1 MB 1.2 MB/s eta 0:00:09
   ------- -------------------------------- 2.1/11.1 MB 1.3 MB/s eta 0:00:07
   -------- ------------------------------- 2.4/11.1 MB 1.3 MB/s eta 0:00:07
   -------- ---------------------------

In [10]:
import pandas as pd
data={'Nama':['Akim','Hanif','rahmat'],
      'usia':[25, 15, 10],
      'kota':['surabaya','bogor','sidoarjo']}
df = pd.DataFname(data)
print(df)

AttributeError: module 'pandas' has no attribute 'DataFname'

In [11]:
import pandas as pd
data={'Nama':['Akim','Hanif','rahmat'],
      'usia':[25, 15, 10],
      'kota':['surabaya','bogor','sidoarjo']}
df = pd.DataFrame(data)
print(df)

     Nama  usia      kota
0    Akim    25  surabaya
1   Hanif    15     bogor
2  rahmat    10  sidoarjo


In [12]:
import pandas  as pd
df  =  pd.read_excel("C:\Data_Siswa.xlsx")
df["Rata_Rata"] = df[["skor_Matematika","skor_fisika"]].mean(axis=1)
df.to_excel("C:\Data_siswa_Hasil.xlsx", index=False)
print(" Data disimpan ke file: Data_Siswa_Hasil.xlsx")

<>:2: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
<>:4: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
<>:2: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
<>:4: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
C:\Users\Muhammad Hanif\AppData\Local\Temp\ipykernel_9052\1912027231.py:2: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
  df  =  pd.read_excel("C:\Data_Siswa.xlsx")
C:\Users\Muhammad Hanif\AppData\Local\Temp\ipykernel_9052\1912027231.py:4: SyntaxWarning: "\D" is an invalid escape seque

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Data_Siswa.xlsx'

In [13]:
import pandas  as pd
df  =  pd.read_excel("C:\Data_Siswa.xlsx")
df["Rata_Rata"] = df[["skor_Matematika",
"skor_fisika"]].mean(axis=1)
df.to_excel("C:\Data_siswa_Hasil.xlsx", index=False)
print(" Data disimpan ke file: Data_Siswa_Hasil.xlsx")

<>:2: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
<>:5: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
<>:2: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
<>:5: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
C:\Users\Muhammad Hanif\AppData\Local\Temp\ipykernel_9052\2601824695.py:2: SyntaxWarning: "\D" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\D"? A raw string is also an option.
  df  =  pd.read_excel("C:\Data_Siswa.xlsx")
C:\Users\Muhammad Hanif\AppData\Local\Temp\ipykernel_9052\2601824695.py:5: SyntaxWarning: "\D" is an invalid escape seque

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Data_Siswa.xlsx'

In [14]:
import pandas as pd

# Ganti path sesuai lokasi file kamu
df = pd.read_excel(r"C:\Users\Muhammad Hanif\Documents\Data_Siswa.xlsx")

df["Rata_Rata"] = df[["skor_Matematika", "skor_fisika"]].mean(axis=1)

df.to_excel(r"C:\Users\Muhammad Hanif\Documents\Data_siswa_Hasil.xlsx", index=False)

print("Data disimpan ke file: Data_Siswa_Hasil.xlsx")


ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

In [15]:
!pip install openpyxl


   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]



In [16]:
import pandas as pd

df = pd.read_excel(r"C:\Users\Muhammad Hanif\Documents\Data_Siswa.xlsx")

df["Rata_Rata"] = df[["skor_Matematika", "skor_fisika"]].mean(axis=1)

df.to_excel(r"C:\Users\Muhammad Hanif\Documents\Data_siswa_Hasil.xlsx", index=False)

print("Data disimpan ke file: Data_Siswa_Hasil.xlsx")


KeyError: "None of [Index(['skor_Matematika', 'skor_fisika'], dtype='object')] are in the [columns]"

In [21]:
import pandas as pd

# Baca file Excel
df = pd.read_excel("C:\\Users\\Muhammad Hanif\\Documents\\Data_Siswa.xlsx")

# Hitung rata-rata dua kolom skor
df["Rata_Rata"] = df[["Skor_Math", "Skor_Fisika"]].mean(axis=1)

# Simpan hasil ke file baru
df.to_excel("C:\\Users\\Muhammad Hanif\\Documents\\Data_Siswa_Hasil.xlsx", index=False)

print("✅ Data disimpan ke file: Data_Siswa_Hasil.xlsx")


PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Muhammad Hanif\\Documents\\Data_Siswa_Hasil.xlsx'

In [22]:
import pandas as pd

# Baca file Excel asli
df = pd.read_excel(r"C:\Users\Muhammad Hanif\Documents\Data_Siswa.xlsx")

# Hitung rata-rata dua kolom skor
df["Rata_Rata"] = df[["Skor_Math", "Skor_Fisika"]].mean(axis=1)

# Simpan hasil ke file Excel baru
df.to_excel(r"C:\Users\Muhammad Hanif\Documents\Data_Siswa_Hasil.xlsx", index=False)

print("✅ Data disimpan ke file: Data_Siswa_Hasil.xlsx")


PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Muhammad Hanif\\Documents\\Data_Siswa_Hasil.xlsx'

In [23]:
import pandas as pd

# Baca file Excel
df = pd.read_excel("C:\\Users\\Muhammad Hanif\\Documents\\Data_Siswa.xlsx")

# Hitung rata-rata dua kolom skor
df["Rata_Rata"] = df[["Skor_Math", "Skor_Fisika"]].mean(axis=1)

# Simpan hasil ke file baru
df.to_excel("C:\\Users\\Muhammad Hanif\\Documents\\Data_Siswa_Hasil.xlsx", index=False)

print("✅ Data disimpan ke file: Data_Siswa_Hasil.xlsx")


PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Muhammad Hanif\\Documents\\Data_Siswa_Hasil.xlsx'

In [24]:
import pandas as pd

# Baca file Excel
df = pd.read_excel("C:\\Users\\Muhammad Hanif\\Documents\\Data_Siswa.xlsx")

# Hitung rata-rata dua kolom skor
df["Rata_Rata"] = df[["Skor_Math", "Skor_Fisika"]].mean(axis=1)

# Simpan hasil ke file baru
df.to_excel("C:\\Users\\Muhammad Hanif\\Documents\\Data_Siswa_Hasil.xlsx", index=False)

print("✅ Data disimpan ke file: Data_Siswa_Hasil.xlsx")

✅ Data disimpan ke file: Data_Siswa_Hasil.xlsx
